version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
