"""rename user_id to reader_id in borrowed_books

Revision ID: 790643d62a03
Revises: 85a2f3245f4d
Create Date: 2025-05-18 21:30:18.585067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790643d62a03'
down_revision: Union[str, None] = '85a2f3245f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.create_foreign_key(None, 'borrowed_books', 'readers', ['reader_id'], ['id'])
    op.drop_column('borrowed_books', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.create_foreign_key(None, 'borrowed_books', 'users', ['user_id'], ['id'])
    op.drop_column('borrowed_books', 'reader_id')
    # ### end Alembic commands ###
